import React from 'react'
import PropTypes from 'prop-types'
import { Container, FooterContent } from './styles'

function Footer(props) {
  const {
    version,
  } = props

  const docs = 'https://harvester.readthedocs.io/en/latest/'
  const repo = 'https://github.com/associatedpress/harvester'

  const apHarvester = (
    <a href={docs}>AP Harvester</a>
  )

  const release = (
    <a href={`${repo}/releases/tag/v${version}`}>{version}</a>
  )

  const openSource = (
    <a href={repo}>open source</a>
  )

  return (
    <Container>
      <FooterContent>
        <p>
          Generated by {apHarvester} version {release}
        </p>
        <p>
          AP Harvester was originally developed by the AP Data Team. It is
          completely {openSource}, so you can help make it better for all of
          us.
        </p>
      </FooterContent>
    </Container>
  )
}

Footer.propTypes = {
  version: PropTypes.string,
}

Footer.defaultProps = {}

export default Footer
